### ISSUE TITLE
[Enhancement]: Azurite v3.26.0

### ISSUE THREAD

**Issue by KSemenenko** [testcontainers/testcontainers-dotnet#1025]
### Problem

new service API version to 2023-08-03 was introdused

### Solution

update to Azurite v3.26.0

### Benefit

latest api

### Alternatives

no

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
You can always override the default version using the `WithImage(string)` API. I do not think it makes sense to continuously update the version of the modules. Additionally, this may introduce breaking changes for others who depend on the module's version (something I would like to avoid). I would prefer to update images only for major versions and only if it is necessary due to incompatibilities.
