### ISSUE TITLE
[Enhancement]: Update mssql default image tag to 2022 from 2019

### ISSUE THREAD

**Issue by Meir017** [testcontainers/testcontainers-dotnet#1189]
### Problem

The default image is `mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04`
see https://mcr.microsoft.com/en-us/product/mssql/server/about

That value hasn't been updated since 2022
![image](https://github.com/testcontainers/testcontainers-dotnet/assets/9786571/641e880c-7854-42c4-81fd-9ed31e897e63)

### Solution

Update the image tag to be `mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04`

### Benefit

More secure and updated docker image

### Alternatives

manually override the image tag when using this library

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
> manually override the image tag when using this library

This is our recommendation. I noticed it is not covered by the best practices. I will update them later today. Usually, we try to avoid updating the default image version to prevent introducing breaking changes for developers when they update the dependency.

**Comment by Meir017** [comment]
@HofmeisterAn can we update the c# example https://testcontainers.com/modules/mssql/ to override the image tag to a more recent one?

**Comment by HofmeisterAn** [comment]
I think the `testcontainers/community-module-registry` repository is public. Could you please create an issue or PR there? This should be the related [line](https://github.com/testcontainers/community-module-registry/blob/0ca74e37e6323ebc9d49c2804e936a5715247594/modules/mssql/index.md?plain=1#L31). Otherwise, @eddumelendez will certainly help you with any further questions or guidance on how to update the version. I am no longer with AJ/Docker.
