### ISSUE TITLE
Clarity on libraries 

### ISSUE THREAD

**Issue by SbiCA** [testcontainers/testcontainers-dotnet#120]
**Is your feature request related to a problem? Please describe.**
I'm a bit confused at the moment I saw that you are a contributor on https://github.com/testcontainers/testcontainers-dotnet. What was the reason you created dotnet-testcontainers instead of continuing on the other one ?

**Describe the solution you'd like**
Maybe add a section to the readme how this relates to testcontainers-dotnet

**Describe alternatives you've considered**

**Additional context**

**Comment by HofmeisterAn** [comment]
Hi @SbiCA, I started this project earlier this year. At that time I already knew the official implementation, but could not use it. Many features are not available or do not work.

At first, I tried to contribute, but unfortunately, the project is not in good shape. It takes/took way to long until PRs get merged. I could not wait that long. I need/needed a solution for my requirements.

I still contribute to the official repository and try to support the development. There's also another implementation here: https://github.com/isen-ng/testcontainers-dotnet. We try to merge all three repositories. However, PRs still take long until they get merged and our progress is pretty slow.

As long as the official implementation does not cover all my requirements, I will work on both projects.

---

**Edit**: Due to the following problems in the official implementation (my opinion), I have decided to do my own implementation. I'll strikethrough the points we did in the first milestone a few weeks ago:

- The code looks like copy and paste from Java.
- It does not feel like a .NET project, e. g. project structure, technologies, language features, naming conventions, etc.
- The released versions do not match with the source code in GitHub.
- I found a bunch of features which are released as NuGet package, but wasn’t in GitHub at all.
- Master branch is/was not compilable (some of the dependencies are incompatible).
- ~~No style rules~~.
- ~~No static code analysi~~s.
- Secure API-Keys etc. are hardcoded in the source code.
- PRs don’t get merged (or have been open for a while).

---

> Maybe add a section to the readme how this relates to testcontainers-dotnet

I think that's a great idea. I'll add a section within the next PR.

I will be happy to answer any further questions.

**Comment by SbiCA** [comment]
@HofmeisterAn that reflects what I detected (only by scratching the surface) so far. Thanks for the honesty and openness. Then I'll try to support you here till merging happened and there is more steadiness on the hopefully merged project.
