### ISSUE TITLE
Ability to execute command in running container 

### ISSUE THREAD

**Issue by oorobets** [testcontainers/testcontainers-dotnet#163]
**Is your feature request related to a problem? Please describe.**
Ability to execute command in running container 

**Describe the solution you'd like**
container.execInContainer(params string[]);

**Describe alternatives you've considered**
None

**Additional context**
For example. I need to run my tests against Solr. Setting it up requires multiple http calls etc.

**Comment by HofmeisterAn** [comment]
I would like to make sure I understand you correctly. You want to execute code after a container has been started (besides `WithCommand`)? This should be very simple. We just need to provide a public method in `IDockerContainer` and delegate the command straight to [TestcontainersClient.ExecAsync](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/f3498a2b00c68806f438a728865469a90a9ef76b/src/DotNet.Testcontainers/Client/TestcontainersClient.cs#L89).

If you like to contribute, I'd be very happy. Otherwise, I can have a look at it within the next days.

**Comment by oorobets** [comment]
> You want to execute code after a container has been started (besides WithCommand)?

That is correct.

> If you like to contribute, I'd be very happy

Yes, I can look into this!

**Comment by HofmeisterAn** [comment]
@oorobets I had a few minutes left on my way home. What do you think about: [feature/exec-command-in-running-container](https://github.com/HofmeisterAn/dotnet-testcontainers/compare/feature/exec-command-in-running-container?expand=1) - sorry did not see your comment.
