### ISSUE TITLE
Wait UntilMessageMessageIsLogged not working 

### ISSUE THREAD

**Issue by sergiutugulschi** [testcontainers/testcontainers-dotnet#352]
using (var consumer = Consume.RedirectStdoutAndStderrToStream(new MemoryStream(), new MemoryStream()))
            {
                var started = "started";
                _googlePubsubContainer = new TestcontainersBuilder<TestcontainersContainer>()
                    .WithCleanUp(true)
                    .WithImage("google/cloud-sdk:emulators")
                    .WithExposedPort(PubsubEmulatorPort)
                    .WithPortBinding(PubsubEmulatorPort)
                    .WithCommand(
                       "/bin/sh",
                       "-c",
                       $"gcloud beta emulators pubsub start --host-port=0.0.0.0:{PubsubEmulatorPort} --project={GcloudProjectName}")
                    .WithOutputConsumer(consumer)
                    .WithWaitStrategy(Wait.ForUnixContainer().UntilMessageIsLogged(consumer.Stdout, started));

                var googleCloudPubsubContainer = _googlePubsubContainer.Build();

                await googleCloudPubsubContainer.StartAsync();
}

I'm running the following code and consumer.Stdout and Stderr are empty, so the output from WithCommand is not written in Stdout, the container is started if I do docker ps I see it in the list but the application hangs because of the wait.

**Comment by HofmeisterAn** [comment]
I'm pretty sure it works. A couple of unit tests covering the output consumer and use its functionality, like:
https://github.com/HofmeisterAn/dotnet-testcontainers/blob/e9db771d5367698605365f67bf0762a8502a9c6c/src/DotNet.Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs#L290

as well as 

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/e9db771d5367698605365f67bf0762a8502a9c6c/src/DotNet.Testcontainers/Containers/Configurations/Databases/CouchbaseTestcontainerConfiguration.cs#L62

I guess something else must be wrong in your case. If you start the container with `docker run` (incl. your command), what output do you get? How does your entrypoint look? Also take a look at `docker logs`.

**Comment by sergiutugulschi** [comment]
Yep, I saw the unit tests, the problem is that OutputConsumer.Stdout retuns empty.

This is the output if I'm running docker run from the console 
![Capture](https://user-images.githubusercontent.com/67583483/101088261-10fbe700-35bc-11eb-8e57-760f5c7141dd.PNG)
So it is strange that OutputConsumer.Stdout gets set as empty.

**Comment by HofmeisterAn** [comment]
The output looks fine, but the `gcloud` command does not write data to `stdout`. Unfourntaly , I'm not familiar with `gcloud`, but I noticed some unexpected behaviors. `.WithCommand("/bin/sh", "-c", "gcloud version")` works fine. It writes data to `stdout` and Testcontainers captures the output.

Even `printf Foo && gcloud beta emulators pubsub start` and `printf Foo || gcloud beta emulators pubsub start` works. At least partial. Testcontainers captures `Foo`.

However, `gcloud beta emulators pubsub start && printf Foo` does not work at all. Testcontainers captures nothing. Please notice; **even** following command won't redirect the output.

```sh
docker run --rm -it google/cloud-sdk:emulators /bin/bash
gcloud beta emulators pubsub start > Foo.txt
```

**The file `Foo.txt` is empty**. That's why I think your problem is more related to the Google container or `gcloud`. Either you find a way to redirect the output or use a different wait strategy e. g. wait until the exposed port is open or block the command until the service is up and running.

```csharp
const int port = 8885;
var testcontainersBuilder = new TestcontainersBuilder<TestcontainersContainer>()
  .WithImage("google/cloud-sdk:emulators")
  .WithCommand("/bin/sh", "-c", $"gcloud beta emulators pubsub start --host-port=0.0.0.0:{port}")
  .WithPortBinding(port)
  .WithWaitStrategy(Wait.ForUnixContainer()
    .UntilPortIsAvailable(port));

await using (IDockerContainer testcontainer = testcontainersBuilder.Build())
{
  await testcontainer.StartAsync();
}
```

**Comment by sergiutugulschi** [comment]
Yep, agree with you, it is something related to gcloud, I also saw that it doesn't output to stdout, I will try another strategy, thank you for your support.

**Comment by HofmeisterAn** [comment]
In the meantime, I’ll close this issue. If you find further information about the `gcloud` behavior don’t hesitate to reopen the issue again. I’m certainly interested in what’s going wrong here.
