### ISSUE TITLE
No such image

### ISSUE THREAD

**Issue by suleimanforever** [testcontainers/testcontainers-dotnet#424]
Hi,

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1694051/154465457-e5b498f2-7d5f-4af6-b7c6-a956c8ddec93.png">
This works locally but in Azure Devops deployment pipeline it gets an error:
`error: Docker API responded with status code=NotFound, response={"message":"No such image: postgres:11.5"}`

Seems to be the same issue as this in the Java version:
https://github.com/testcontainers/testcontainers-java/issues/3574#issuecomment-742080370
https://github.com/testcontainers/testcontainers-java/pull/3575

// Suleiman

**Comment by HofmeisterAn** [comment]
Which Docker registry do you use? Did you try `docker pull postgres:11.5`?

**Comment by suleimanforever** [comment]
There is no issue when I run it locally, only in the build pipeline on
Azure.
Not sure about the build agents configuration, but not being able to reach
the Docker registry could be the issue.
We use Azure Container registry (ACR). Is there any way to specify which
Docker registry?

Regards
Suleiman

Den tors 17 feb. 2022 kl 15:20 skrev Andre Hofmeister <
***@***.***>:

**Comment by HofmeisterAn** [comment]
> There is no issue when I run it locally, only in the build pipeline on

Well, then run the command on your pipeline.

> We use Azure Container registry (ACR). Is there any way to specify which Docker registry?

You're probably [logged](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#login) into your private registry. Maybe `docker pull docker.io/postgres:11.5` will work, or login to a registry that has the image. There is also `WithRegistryAuthentication`, dunno if it works with the default registry `docker.io`.

**Comment by ptimothee** [comment]
Hey,
I seem to be having the exact same issue. I can provide some details if is can help. Please see stackTrace below. It suggest that actually that the image was actually pulled, but for some reason when using azure pipeline the application is not able to create the container it just downloaded with the error that it cannot be found. I believe the issue is an environment problem given that this works as expected locally.

Browsing the repo, I also notice that the builds are using azure pipeline which means that is can be setup to work there but I'm not sure what the difference is. For now I set it up to use my own hosted machine but I'm trying to figure out if i can used the azure provide machine (like window latest). Also if using a private repo wondering if i can set it up to not have credential in code using WithRegistryAuthentication

```
[xUnit.net 00:00:09.99]       Docker.DotNet.DockerContainerNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu"}
[xUnit.net 00:00:09.99]       Stack Trace:
[xUnit.net 00:00:10.00]            at Docker.DotNet.ContainerOperations.<>c.<.cctor>b__29_0(HttpStatusCode statusCode, String responseBody)
[xUnit.net 00:00:10.00]            at Docker.DotNet.DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
[xUnit.net 00:00:10.00]            at Docker.DotNet.DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
[xUnit.net 00:00:10.00]            at Docker.DotNet.ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
[xUnit.net 00:00:10.00]            at DotNet.Testcontainers.Clients.DockerContainerOperations.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
[xUnit.net 00:00:10.00]            at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
[xUnit.net 00:00:10.00]            at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.Create(CancellationToken ct)
[xUnit.net 00:00:10.00]            at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.StartAsync(CancellationToken ct)
```

So again seems like library is working as expected, so awesome work there, but any insight or recommendation you can provide with pipeline setup would be greatly appreciated.

**Comment by HofmeisterAn** [comment]
> Also if using a private repo wondering if i can set it up to not have credential in code using WithRegistryAuthentication

There are different ways to login into a Docker registry before pulling an image. For, `WithRegistryAuthentication` you could use environment variables too. All pre-configured containers "pulls" from https://hub.docker.com/. Maybe this will work:

```cs
new PostgreSqlTestcontainerConfiguration("docker.io/postgres:11.5")
{
  Database = "db",
  Username = "postgres",
  Password = "postgres",
}
```

> using azure pipeline the application is not able to create the container

Indeed, the stack trace looks unusual. Did you double-check, if the pipeline really pulled the image? I guess, that the pull "fails" too, but just don't throw an exception.

----

**Edit**: It looks like pulling a "non-existing" images does not throw an exception. `WithImage("FooBarBaz:1.0.0")` behaves exactly the same. You'll get the error in `CreateContainerAsync`.

E.g. Artifactory caches Docker images from repositories on demand and supports a single entrypoint. It really depends on how your pipeline etc. is configured. If we found a proper solution for you, we can create a discussion to share best practices with others.

**Comment by HofmeisterAn** [comment]
I'll close this issue for inactivity. Don't hesitate to reopen it again if you have any further questions. As I said, the problem is more related to your infrastructure. Collecting best practices would be still nice.

**Comment by InspiringCode** [comment]
[This post on StackOverflow](https://stackoverflow.com/questions/76023326/azure-hosted-build-agent-fails-to-find-docker-image-with-error-no-such-image) gave a good hint and looking deeply into the Pipeline logs indeed confirmed that this is  a problem:

```[testcontainers.org 00:00:03.30] image operating system "linux" cannot be used on this platform: operating system is not supported```

Trying to migrate my pipeline to 'ubuntu-latest' now.

**Comment by KUTlime** [comment]
For those, who landed here like me...

Indeed, `postgre:latest` is a Linux-based image, see the page [here](https://hub.docker.com/_/postgres), or explanation [here](https://forums.docker.com/t/docker-no-matching-manifest-for-windows-amd64-10-0-19044-in-the-manifest-list-entries/134062).

If CI/CD agent is based on Windows (_windows-latest => Windows Server 2022 when I write this comment_), e.g., a SonarQube integration job, the agent doesn't have WSLv2 enabled, hence, having problems with Linux images.

## Solution 1

Migrate to e.g., `runs-on: ubuntu-latest`.

## Solution 2

Migrate to `runs-on: windows-2025` which should have WSLv2 enabled, when I tested it, it didn't work. 🙁

**Comment by bjuraga** [comment]
I have this same issue. For context:
Running locally works, running in Azure DevOps, on a linux build agent, authenticated towards ACR fails.

I have a dockerfile that is based on an image in our private ACR, so the agent is authenticated and that part works.

But, i want to build the image locally as part of a CI test run. Then start a container running it. 
However, docker cli on behalf of testcontainers tries to pull this image from our ACR, not locally.
This image is not pushed to ACR, so normally i get image not found. 

Any ideas how to setup docker cli to pull images first from it's local registry (on the build agent) then ACR?

**Comment by bjuraga** [comment]
There is some magic done that i don't know (yet) how to disable. The Image Full Name that ends us used by the container is prepended by `{OUR_ACR_FQDN}/docker/`. 

Logs:
```
[DEBUG]: Created image with full name: localhost/testcontainers/fc3f2113-df70-4d62-a08a-bce8af586bef:latest
[DEBUG]: the container used the image: {OUR_ACR_FQDN}/docker/localhost/testcontainers/fc3f2113-df70-4d62-a08a-bce8af586bef:latest
```

This seems like a bug?

Repro:
```
 var imageTask = new ImageFromDockerfileBuilder()
   .WithDockerfileDirectory(CommonDirectoryPath.GetProjectDirectory(), "../../../")
   .WithDockerfile("api.dockerfile")
   .WithDeleteIfExists(false)
   .Build();

 imageTask.CreateAsync().ConfigureAwait(false).GetAwaiter().GetResult();
 
 Console.WriteLine($"[DEBUG]: Created image with full name: {string.Join("_", imageTask.FullName.ToCharArray())}");

 container = new ContainerBuilder()
   .WithImage(imageTask.FullName) // <-- also tried with the image instance
   .WithImagePullPolicy(PullPolicy.Missing)
   .WithPortBinding(8080, 8080)
   .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(8080))
   .Build();

 Console.WriteLine($"[DEBUG]: the container is using an image with full name: {string.Join("_", container.Image.FullName.ToCharArray())}");
```

The logging adds '_' to prevent  AzureDevOps masking the FQDN

**Comment by bjuraga** [comment]
@HofmeisterAn would you consider opening this up again?

**Comment by HofmeisterAn** [comment]
This issue is about using a wrong or incompatible image. The author tried to use a Linux image on a host that only supports Windows images.

I'm not sure I fully understand your setup or the actual issue.

> Any ideas how to setup docker cli to pull images first from it's local registry (on the build agent) then ACR?

Testcontainers pull base images if they're **not** already cached locally. This is necessary, otherwise, we wouldn't be able to build the image at all.

https://github.com/testcontainers/testcontainers-dotnet/blob/8470afdac8c6a3236a940af77ab643494daa463c/src/Testcontainers/Clients/TestcontainersClient.cs#L385

Are you sure the locally cached base image has the exact same name/tag? Do you pass the name/tag via build args?

https://github.com/testcontainers/testcontainers-dotnet/blob/8470afdac8c6a3236a940af77ab643494daa463c/src/Testcontainers/Images/DockerfileArchive.cs#L105-L106

> The Image Full Name that ends us used by the container is prepended by `{OUR_ACR_FQDN}/docker/`.

Are you using the configuration [`TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX`](https://dotnet.testcontainers.org/custom_configuration/)? It prepends the name and substitutes the Docker Hub registry.

**Comment by bjuraga** [comment]
The original issue from 2022 is exactly what i am facing as an error now. 

I don't fully understand the last few posts here about OS differences, those comments from 2024 do seem unrelated. So i will either ignore those or if you like i can start a new issue?


I did post the code to reproduce the issue i am facing. Basically, i create an image from a local dockerfile. It gets a name and a tag. I posted the image name as well higher. 

Now, the core of the issue is that the container that i create based on that image, regardless if i pass in the IImage or a string for the image full name, the code of the container builder changes the name of the image. 

It does not change it on my local machine, but it does if i run it in my Linux Azure Build Agent that runs docker in docker. I found some code that does check if i am running inside of a docker container, and that one sets some prefixes, but that is a bug. It changes the behavior for me magically. I posted the changed image name as well higher. It prefixes it with the ACR fqdn, but it should not. 

If i SSH into the build agent, i do see the correct, un prefixed image for about 40 seconds before it gets cleaned up.

Imagine planning to start a container with exactly this image name 'nginx:latest' and your container builder steps in saying no, i know better, it should be 'acr.azurecr.io/docker/nginx:latest' .

**Comment by HofmeisterAn** [comment]
> If i SSH into the build agent, i do see the correct, un prefixed image for about 40 seconds before it gets cleaned up.

[Ryuk](https://dotnet.testcontainers.org/api/resource_reaper/) cleans up resources after the test finishes, whether it succeeds or fails.

> Imagine planning to start a container with exactly this image name 'nginx:latest' and your container builder steps in saying no, i know better, it should be 'acr.azurecr.io/docker/nginx:latest' .

That's exactly what the configuration mentioned above does. Are you using the image name prefix custom configuration? Try and add the following configuration to the image builder:

```
WithName(new DockerImage("localhost/testcontainers/foo", null, null, null, TestcontainersSettings.HubImageNamePrefix))
```

If it's still not working, please create a new issue. But we'll need more information about your environment then: DinD configuration, environment variables, the `~/.testcontainers.properties` file, etc.

**Comment by bjuraga** [comment]
I just confirmed that the magic value is indeed set on the container as an environment variable `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX`. 

I will try the workaround you suggested, and if it works i will use it for now. I am new to testcontainers, but this override seems a bit strange. Might as well be that we are not using it correct. 

Thanks!

**Comment by suleimanforever** [comment]
Hi,

@Andre are you saying that if using Azure Pipelines (like I was at the
time, that
for example vmImage should be something Linux based like Ubuntu, like in
the image?


@bjuraga Can you provide more information about
TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX?

**Comment by bjuraga** [comment]
I cannot provide more info, i guess it is documented somewhere. 

The override did not work, so i have to conceede and just tag the image i build locally with the same prefix, manually. It will be confusing for people in the future trying to debug why that image is not in the ACR but is tagged as if it is, but for me, case closed

**Comment by HofmeisterAn** [comment]
> I just confirmed that the magic value is indeed set on the container as an environment variable `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX`.
> 
> I will try the workaround you suggested, and if it works i will use it for now. I am new to testcontainers, but this override seems a bit strange. Might as well be that we are not using it correct.
> 
> Thanks!

The configuration is designed to allow developers to redirect image pulls to their private registry instead of Docker Hub. This helps avoid rate limits and ensures that images are cached and always available.

One likely issue is that the container builder respects the configuration, but the image builder does not. This is probably something we can easily fix and improve. I assume this won't cause any breaking changes. See the following differences:

https://github.com/testcontainers/testcontainers-dotnet/blob/8470afdac8c6a3236a940af77ab643494daa463c/src/Testcontainers/Builders/ContainerBuilder%603.cs#L95-L105

https://github.com/testcontainers/testcontainers-dotnet/blob/8470afdac8c6a3236a940af77ab643494daa463c/src/Testcontainers/Builders/ImageFromDockerfileBuilder.cs#L63

If the prefix is set, the image builder should likely respect it too.

I still believe this are different issues. The initial issue does not include the image builder.

**Comment by bjuraga** [comment]
That sounds like a good idea to unify the behavior.
