### ISSUE TITLE
How to set up github actions to do integration tests

### ISSUE THREAD

**Issue by maranmaran** [testcontainers/testcontainers-dotnet#452]
Greetings I can't seem to make testcontainers play well with my github action.

Could you help me out

XUnit async class fixture code:

        var dockerEndpoint = Environment.GetEnvironmentVariable("DOCKER_HOST");
        Console.WriteLine("Connecting to docker endpoint: " + dockerEndpoint);

        Container = new TestcontainersBuilder<MsSqlTestcontainer>()
            //.WithExposedPort("1433")
            .WithDatabase(new MsSqlTestcontainerConfiguration()
            { Password = DatabasePassword })
            .WithDockerEndpoint(dockerEndpoint)
            .WithCleanUp(true)
            .Build();

        await Container.StartAsync();
        // Container never starts or throws connection refused
        // Depends on which docker host I give it

Github action code: 

    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Test
        run: |
          echo "Docker Images - this command works if given unix:///var/run/docker.sock as docker host or without env"
          docker image ls
          
          echo "Integration tests - these don't run containers - don't know which docker_host"
          dotnet test MySolution.sln
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
   
I'm having trouble knowing which DOCKER_HOST variable to give and what exactly to do.

I've tried adding service container docker:dind with github actions and exposing it on port 2735 but that also didn't work for me.
So far I was unsuccessful in finding similar actions. 

Could you point me please in right direction?

**Comment by HofmeisterAn** [comment]
> I'm having trouble knowing which DOCKER_HOST variable to give and what exactly to do.

Setting the Docker endpoint shouldn't be necessary for GitHub. Here is a small [example](https://github.com/HofmeisterAn/dotnet-testcontainers/compare/github/issue-452?expand=0) that runs fine on GitHub without any additional configuration. As far as I know, GitHub uses the same images as Azure. [This](https://github.com/HofmeisterAn/dotnet-testcontainers/runs/6308358140?check_suite_focus=true#step:4:32) is the corresponding pipeline run.

Be aware, .NET Testcontainers does not consider the Docker credential store yet to pull private images. I'm working on that #444. If you need private images, you can pull them either in advance or use the mentioned `WithRegistryAuthentication`.

**Comment by maranmaran** [comment]
Love it, thanks for quick response.

Yeah works fine sorry. I kind of misdirected myself. 
Containers are running fine actually. 

However, I get connectivity issues and timeouts towards my sql database inside these containers. That's why I kind of assumed they didn't even start up...

Is this related to host / bridge networks on my default vm runner (ubuntu-latest)?  

I've tried creating networks, passing in host network, increasing timeout.

`Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.`

**Comment by HofmeisterAn** [comment]
Based on your information, I can't say what's going wrong. It looks like you're messing a few things up. You're mentioning configurations that shouldn't be necessary (at least not when you start with). Maybe the MSSQL unit tests will help you. They run on the same infrastructure — GitHub ~ Azure. Otherwise, I need more information like stack trace, code, etc.

Take a look into the tests we're using here:

- [MsSqlFixture](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/982e736b513b5d225c4263d7d0a529db2a339042/tests/DotNet.Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/MsSqlFixture.cs)
- [MsSqlTestcontainerTest](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/982e736b513b5d225c4263d7d0a529db2a339042/tests/DotNet.Testcontainers.Tests/Unit/Containers/Unix/Modules/Databases/MsSqlTestcontainerTest.cs)
- Related [test run](https://dev.azure.com/HofmeisterAn/GitHub-Testcontainers/_build/results?buildId=2197&view=logs&j=fc799872-1c04-54a5-6e88-3d69a0bc5800&t=269ecb81-d06e-5b7a-6cbc-53fd2b52286d&l=94)

**Comment by maranmaran** [comment]
Ok this is my side.

My setup was to run the containers. My business needs implement certain import mechanism for the data. 

The implementation uses SqlBulkCopy. 
This was timing out. 

Increased the timeout and all went fine and dandy.

**Comment by maranmaran** [comment]
Thanks for your help, beautiful work.
