### ISSUE TITLE
Support for RavenDb

### ISSUE THREAD

**Issue by Morasiu** [testcontainers/testcontainers-dotnet#518]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a native support for RavenDb container.

**Describe the solution you'd like**
Just a support for RavenDb container.

**Additional context**
You can find more info about RavenDB in containters [here](https://ravendb.net/docs/article-page/5.4/csharp/start/installation/running-in-docker-container). Hope this helps.

**Comment by PureKrome** [comment]
❤️ RavenDB! That said, RavenDb does have an inmemory version which is actually a -real- version (not 'in-memory like EntityFramework which is not like a real version of a db) .. and it's really good/works.

But having a strongly typed class that supports RavenDb would be so nice because then we could create custom images based of RavenDb which could already include some seeded data and boom!!! tests would be all ready to go .. each time!

**Comment by HofmeisterAn** [comment]
Sounds great. Either, we add the support with the current limitations of modules #493, or we use RavenDb as the first module that participates from the new structure and deployment mechanisms.

I'll finish a feature for `Docker.DotNet` in the next days. Then I can start with #493. It would be great if someone would like to join. The modules will benefit a lot from different opinions and perspectives.

**Comment by HofmeisterAn** [comment]
I will start to take a look into this.
