### ISSUE TITLE
Authentication Error on Mongo DB

### ISSUE THREAD

**Issue by rodrigomocca** [testcontainers/testcontainers-dotnet#637]
**Describe the bug**
When trying to connect to Mongo I'm getting this error:
MongoDB.Driver.MongoAuthenticationException : Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1.

**To Reproduce**
1. On Startup file create the containers
2. Inject IMongoDatabase on a class

**Expected behavior**
Connect to database

**Screenshots**
![image](https://user-images.githubusercontent.com/4087916/197818124-f028f948-e685-4320-8fd5-ab58f5526dfe.png)
![image](https://user-images.githubusercontent.com/4087916/197818395-1ade0d03-d057-423a-bd22-d8b5429e54c6.png)

**Desktop (please complete the following information):**
- Version 11

**Additional context**
In some pcs is runnning as expected, but in others it throws the Authentication exception mentioned above.
In the pipeline is failing.

Do you have any ideas why this is happening?

**Comment by HofmeisterAn** [comment]
Start the container before accessing the `ConnectionString` property. Line 50 in your first screenshot blocks the async context too, that is not recommended.

**Comment by HofmeisterAn** [comment]
Have you been able to fix your issue? Do you need any further help?

**Comment by HofmeisterAn** [comment]
We will close this issue, due to no response. Please notice the current MongoDB module supports version 5. Previous or later versions may not run with the default module configuration. I think for version 4, `mongosh` is missing. You can always use the generic approach to configure different versions.

Do not hesitate to reopen the issue again in case you need any help.
