### ISSUE TITLE
Problem with using Mongo latest version image

### ISSUE THREAD

**Issue by mehdihadeli** [testcontainers/testcontainers-dotnet#734]
### Testcontainers version

2.3.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x64

### .NET version

7

### Docker version

```shell
4.7.1
```

### Docker info

```shell
.
```

### What happened?

Hi,

Testcontainers MongoDB module hangs with the latest Docker image (`mongo:latest`).

**Comment by HofmeisterAn** [comment]
Not all pre-configured module configurations are compatible with every image version, like MongoDB. The latest MongoDB Docker image (version 6) has breaking changes. The module configuration relies on version 5. Testcontainers for .NET "hangs" with version 6, because the container never gets to the state that it is ready to use (completes the wait strategy). Basically, we need to fix the wait strategy, I mentioned it here: https://github.com/testcontainers/testcontainers-dotnet/discussions/636#discussioncomment-3958297.

**Comment by mehdihadeli** [comment]
Thanks, For now I switched to default version on mongo test containers and it works

**Comment by HofmeisterAn** [comment]
Something we can address with the migration to the new module API. Either we add dedicated builder for specific MongoDB versions or we change the wait strategy internally depending on the version.

**Comment by mehdihadeli** [comment]
I think second one has fewer changes

**Comment by mehdihadeli** [comment]
@HofmeisterAn Is there any sample for using new module?

**Comment by HofmeisterAn** [comment]
Module specific documentations are not yet done, but you can take a look at the corresponding tests:
https://github.com/testcontainers/testcontainers-dotnet/blob/3133a565064385f72b3272591c82cd2f8b76f997/tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs#L51-L76

**Comment by mehdihadeli** [comment]
Thanks.
