### ISSUE TITLE
TestcontainersBuilder deprecation

### ISSUE THREAD

**Issue by r-work** [testcontainers/testcontainers-dotnet#750]
Hi, maybe it's just me, but the deprecation seems a bit confusing, if I change the following:

```C#
private readonly TestcontainerDatabase _postgresqlContainer = new TestcontainersBuilder<PostgreSqlTestcontainer>()
.WithDatabase(new PostgreSqlTestcontainerConfiguration
{
    Database = "db",
    Username = "postgres",
    Password = "postgres",
})
.Build();
```

to:
```C#
private readonly TestcontainerDatabase _postgresqlContainer = new ContainerBuilder<PostgreSqlTestcontainer>()
.WithDatabase(new PostgreSqlTestcontainerConfiguration
{
    Database = "db",
    Username = "postgres",
    Password = "postgres",
})
.Build();
```
I'm still getting the "obsolete" warning, what do I need to do?
Thanks

**Comment by HofmeisterAn** [comment]
I am sorry for the inconvenience, by using the module builder you cannot get ride of the obsolete warning yet 😬. Since the generic and module builder sharing the same syntax, we can not distinguish between them and use the obsolete flag for one but not the other.

With the next release `2.5.0` every module will have its own builder, for PostgreSQL it will be `PostgreSqlBuilder`.

- `TestcontainersBuilder<TestcontainersContainer>()` = generic builder → `ContainerBuilder()` (obsolete intended).
- `TestcontainersBuilder<PostgreSqlTestcontainer>()` = module builder → `PostgreSqlBuilder()` (with 2.5.0).

If the warnings bothers you, I would recommend to disable it for now:

```csharp
#pragma warning disable 618
private readonly TestcontainerDatabase _postgresqlContainer = new TestcontainersBuilder<PostgreSqlTestcontainer>()
#pragma warning restore 618
```

_If you heavily rely on modules, it might make sense to wait until 2.5.0 is available. 2.4.0 Is a kind of intermediate release that contains necessary preparations._

Sorry again.

**Comment by r-work** [comment]
@HofmeisterAn thanks for the speedy reply.

No problem, was just wondering what I needed to do, I will leave it as it is, and change it once `2.5.0` is out.

And thanks for the library, really helpful.

**Comment by HofmeisterAn** [comment]
I agree that the message is unfortunate after looking at it again. I will try to complete the migration ASAP.

**Comment by HofmeisterAn** [comment]
FYI: You will find the refactored modules [here](https://github.com/testcontainers/testcontainers-dotnet/tree/develop/src). We will publish them as NuGets soon as the other modules got replaced.
