### ISSUE TITLE
[Enhancement]: Support docker compose

### ISSUE THREAD

**Issue by vs-savelich** [testcontainers/testcontainers-dotnet#995]
### Problem

Would be nice to have DockerComposeModule, like in Java implementation: https://java.testcontainers.org/modules/docker_compose/

### Solution

Probably Java implementation can be used as a starting point.

### Benefit

Simpler setup, less ceremony around creating and running containers.

### Alternatives

Not sure

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
Thank you for bringing up this matter. There is already an existing issue (https://github.com/testcontainers/testcontainers-dotnet/issues/122) related to the same topic, I will close this one to avoid scattering the discussion across multiple issues. Please don't hesitate to share your ideas and suggestions in the mentioned issue. Since you are interested in contributing, perhaps you can collaborate with others (there are others who share an interest in this feature too) on implementing it. I'm happy to assist too.
